### ISSUE TITLE
How do we formally represent the SHR specification?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#17]
The definition (specification) of the SHR should be computable. Some choices include grammar (ANTLR4),  archetype description language (ADL), model driven health tools, UML, ART-DECOR, FHIR profiles, or roll-your-own.

**Comment by jsnichols** [comment]
Which of these choices best support your design principle of "normalized English language"? Is there a clearly superior choice based on this feature alone?

Apart from "normalized English language," what are the other key technical design principles that you are factoring?

Can you identify the technical tradeoffs between the above 6 approaches to formal representation? Are they knowable at this stage? 

Do you have a top 3 among these list of choices? Could you prototype a small subset of SHR data in these 3 formats so that we can play with/break it? 

What additional information do we need in order to select a formal representation for the SHR specification?
