### ISSUE TITLE
We need a well defined list of compelling "clinical pulls" that SHR enables

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_design#36]
From: owner-standard-health-record-10x-list@lists.mitre.org [mailto:owner-standard-health-record-10x-list@lists.mitre.org] On Behalf Of Sleeper, Harry A.
Sent: Saturday, June 25, 2016 7:07 AM
To: standard-health-record-10x-list US Standard Health Record Design standard-health-record-10x-list@lists.mitre.org
Cc: Quina, Andre C. aquina@mitre.org; Walonoski, Jason A. jwalonoski@mitre.org
Subject: SHR "Clinical Pulls" List

We need a well defined list of compelling "clinical pulls" that SHR enables in the SHR-10x brief.

EG, ...
1. Complete, merged, accurate patient health records at each patient-clinician encounter.
2. Reduced EHR data entry burdens
3. Reduced gaps in the patient health record through tracking SHR completeness 

...

N-3. Rapid progress toward the "hands-free", auto-documenting, conversational patient-clinician encounter (SHR_grammar simplifies Nurse Echo).

...

N. Increased patient participation in their care with increased patient services acting on their SHR.

Joey/Susan------Can you help here?

We also need "patient pulls" and "payer pulls".

...H

**Comment by susanhaas** [comment]
Structured primarily for medical, public health, and self-care rather than structured primarily for billing:
1.       Computable: clinician seeing patient can pull together in one place all information relating to a certain care need (vs now clinician has to page through stacks of individual entries organized by date. Often the clinician spends time typing/dictating a summary of those findings to serve as a reference for the future)
2.       Interoperable: ditto #1 across systems (hospitals, ambulatory, EMS, public health clinics, vital statistics functions, pharmacies, prisons, etc)
3.       Interoperable within a system. In June I visited a hospital with 143 separate computer systems.  I’m sure some were billing, HR, and ordering etc but most were clinical.
4.       Patient engagement supported as a design feature by providing access from the beginning vs added into select modules along the way
5.       Integration of SDOH as a primary focus rather than as a list in the “social history” component of the EMR.
6.       Utility for community based interventions: neighbors get care in different systems. With interoperable systems hot-spotting and focused community interventions can be supported.

-Susan
